# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdN_j6zNZeQ-G8edipDP3FDUXY-JLuhw
"""


import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import numpy as np
from PIL import Image
import os

def load_road_model():
    return load_model("road_damage_classifier.keras")

model = load_road_model()

class_names = ['cluster_0', 'cluster_1', 'cluster_2', 'cluster_3']

st.title("Road Damage Classifier")
st.markdown("Upload an image of a road, and an AI will classify the type of damage.")

uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file).convert('RGB')
    st.image(img, caption='Uploaded Image', use_column_width=True)

    img_resized = img.resize((224, 224))
    img_array = image.img_to_array(img_resized)
    img_array = preprocess_input(img_array)
    img_array = np.expand_dims(img_array, axis=0)

    predictions = model.predict(img_array)
    predicted_class = class_names[np.argmax(predictions)]

    st.subheader("Prediction:")
    st.success(f"This looks like: **{predicted_class}**")